theme = "monokai_pro"

[editor]
# gutters = ["diagnostics"]
mouse = true
clipboard-provider = "wayland"

[editor.lsp]
display-messages = true

[keys.normal]
C-s = ":write-all"

[keys.insert]
C-s = [":write-all", "normal_mode"]
