theme = "catppuccin_moccha"

[editor]
# gutters = ["diagnostics"]
true-color = true
mouse = true
auto-pairs = false
soft-wrap.enable = true
clipboard-provider = "wayland"

[editor.lsp]
display-messages = true

[keys.normal]
C-s = ":write-all"

[keys.insert]
C-s = [":write-all", "normal_mode"]
