[language-server.csharp-ls]
command = "csharp-ls"

[language-server.allium-lsp]
command = "allium-lsp"
args = ["--stdio"]

[[language]]
name = "allium"
scope = "source.allium"
file-types = ["allium"]
comment-token = "--"
language-servers = ["allium-lsp"]

[[grammar]]
name = "allium"
source = { git = "git@github.com:juxt/tree-sitter-allium", rev = "728f4d3410894da3b74507003c95282042d50f8b" }

[[language]]
name = "c-sharp"
language-servers = ["csharp-ls"]
