[language-server.csharp-ls]
command = "csharp-ls"

[language-server.allium-lsp]
command = "allium-lsp"
args = ["--stdio"]

[[language]]
name = "allium"
scope = "source.allium"
file-types = ["allium"]
comment-token = "--"
language-servers = ["allium-lsp"]

[[language]]
name = "c-sharp"
language-servers = ["csharp-ls"]

[language-server.jdtls]
command = "jdtls"

[[language]]
name = "java"
language-servers = ["jdtls"]
