set shell=/bin/sh " avoid errors caused by using exotic shells e.g. fish

"completion
set completeopt=menuone

"the sane settings
set shiftwidth=4
set tabstop=4
set softtabstop=4
"expand tabs into spaces
set expandtab
set autoindent
set smartindent
set smarttab

"highlighting
syntax on

" search and replace
set ignorecase
set hlsearch
set incsearch

" Tmux/terminal-related
set notimeout
set ttimeout
set timeoutlen=50

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" show a completion popup for commands
set wildmenu

set wildignorecase "case-insensitive filename completion
set wildignore+=tags,*.so,*.swp,*.bak,*.pyc,*.pyo,*.min.*js,*.min.*css,*.zip
set wildignore+=*/node_modules/*
set wildignore+=*/platforms/android/*
set wildignore+=*/platforms/ios/*

set path=**

if executable("rg")
    set grepprg=rg\ --vimgrep\ --no-heading
    set grepformat=%f:%l:%c:%m,%f:%l:%m
endif

autocmd QuickFixCmdPost *grep* cwindow

" Don't blink at me!
set novisualbell
" And now stop the blinking too.
set vb t_vb=

"set the GUI 'current' folder relative to the buffer
set browsedir=buffer

"configure a monospace font that supports cyrillic
set guifont=DejaVu\ Sans\ Mono\ 12

set guioptions-=T "No toolbar
set guioptions-=m "No menubar
set guioptions-=r "No right scrollbar
set guioptions-=R "No right scrollbar
set guioptions-=l "No left scrollbar
set guioptions-=L "No left scrollbar

" Save UI space
set nonumber

"Set xterm terminal title
set title
"Shorter messages
set shortmess=atI

set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands

"setup window
if has("gui_running")
    "winpos 0 0
    set lines=56
    set columns=140
endif

set ttyfast
set laststatus=2

set nocompatible

set t_Co=256
set background=dark
let g:zenburn_old_Visual = 1
colorscheme zenburn

"autosave buffers
set autowriteall

"unicode options. we want utf-8 and no BOM symbols
set encoding=utf-8
setglobal fileencoding=utf-8
set nobomb

"don't litter with annoying files when opening a file
set nobackup
set nowritebackup
set noswapfile
set nofoldenable

"Hide abandoned buffers in order to not lose undo history.
set hidden
"Moar history!
set history=1000
if has('persistent_undo')
    set undolevels=5000
    set undodir=$HOME/.cache/vim/undo
    set undofile
endif

"look for tags files in the current folder and work up
"the dir tree if not found.
set tags=./tags;/

" show trailing whitespace as dots
set list listchars=tab:·\ ,trail:·


let g:GPGDefaultRecipients = ["hristo@deshev.com"]

"
let g:typescript_indent_disable = 1
let g:js_indent_typescript = 1

let g:NERDSpaceDelims = 1

let g:apex_backup_folder="/tmp/apex/backup"
let g:apex_temp_folder="/tmp/apex/temp"
let g:apex_properties_folder="/tmp/apex/properties"
